### ISSUE TITLE
Reverse zone not recognized as reverse if name is uppercase

### ISSUE THREAD

**Issue by JanuszU** [vinyldns/vinyldns#957] opened 2020-07-02 12:48 UTC
**Describe the bug**
if connected zone is named ie. "0.1.10.IN-ADDR.ARPA" it is not recognized as reverse zone. PTR records are not valid  

**VinylDNS Version**
0.9.5-SNAPSHOT

**To Reproduce**
1. connect a reverse zone and name it uppercase
2. try add a new PTR rr
4. See error: "...PTR is not valid in forward lookup zone"

**Expected behavior**
both upper and lower case names should work

**Comment by pauljamescleary** [comment] 2020-07-02 14:30
Oh, that is unfortunate.  We have seen this a few times.  The original DB was all DynamoDB where things were case insensitive by default.  Moving to MySQL exposed some of these issues.

This should be a small fix.  Just need to craft he SQL to do "lower" here - https://github.com/vinyldns/vinyldns/blob/61c6338bee7e998e427b65ff1b9642c02b6f3135/modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneRepository.scala#L219

**Comment by pauljamescleary** [comment] 2020-07-02 14:32
Also, we had discussed in the past to make it much more robust to do reverse zone discovery. 

I have to look into MySQL, but with Postgres they have a `cidr` type and you can see if an IP address is in the range.  We could also add a start/end (range) on the zone table and see if an IP address falls in the range.  Right now zone discovery for reverse zones is a bit wonky.

**Comment by remerle** [comment] 2020-07-02 15:14
MySQL supports case-insensitive collations.

@JanuszU what is the result of this query against your MySQL database
```sql
SELECT table_schema, table_name, table_collation
       FROM information_schema.tables WHERE table_name = 'zone';
```

**Comment by JanuszU** [comment] 2020-07-06 06:27
the result is:  

table_schema | table_name | table_collation |  
vinyldns | zone | utf8mb4_general_ci

**Comment by pauljamescleary** [comment] 2020-07-15 13:34
hmmm, I would think `utf8mb4_general_ci` case insensitive

**Comment by pauljamescleary** [comment] 2020-08-28 14:57
@JanuszU did you have any update, feels like something we can get in :)

**Comment by remerle** [comment] 2020-09-03 19:13
Marking this as Ready.  Someone can pick it up, try to reproduce and see if it's a matter of the collation or if it's something we should account for in the code.

I'd like to avoid handling case in the code, since it can cause table scans if your data is collated as case-sensitive.

**Closed** 2022-05-19 19:43 UTC
Labels: kind/bug, status/ready
