### ISSUE TITLE
Users cannot include groups to which they do not belong in zone ACLs 

### ISSUE THREAD

**Issue by remerle** [vinyldns/vinyldns#1119] opened 2022-04-29 13:22 UTC
## Description
The purpose of the ACL on zones is to enable control over who can access the zone. This could, very conceivable, include groups to which I, as a user, do not belong.

Say that I have a zone, `vinyldns.io` that is private. I and the users in the administrative group can modify the records 👍 - all good.

Now, let's say that I want to give access to the group `DB Administrators` for records that contain `^.*db.*$` but I am not in the group `DB Administrators`. At present, there is no way for my to allow access, even though I am a zone administrator, and the zone is private.

In fact, the only users that can do this would be super users.

Arguably, the only users that can truly decide whether to allow access would be the private owners. So, this puts an unnecessary burden on teams supporting VinylDNS.

## Resolution
Update the API and Portal where necessary to support/display the full list of groups in the dropdown for the zone ACL editor view.

**Comment by jhg03a** [comment] 2022-04-29 21:10
Is this a duplicate of #993

**Closed** 2022-05-20 13:41 UTC
Labels: kind/bug, good first issue, status/ready, area/portal
