### ISSUE TITLE
Make it easier for a user of the API to add members to groups

### ISSUE THREAD

**Issue by iamjarvo** [vinyldns/vinyldns#676] opened 2019-06-04 18:03 UTC
At this time the Vinyl API expects a user to pass in ids to the `member` and  `admin` fields. 

```
{
  "name": "some-group",
  "email": "test@example.com",
  "description": "an example group", 
  "members": [
    {
      "id": "2764183c-5e75-4ae6-8833-503cd5f4dcb0"
    }
  ],
  "admins": [
    {
      "id": "2764183c-5e75-4ae6-8833-503cd5f4dcb0"
    }
  ]
}
```

When using the API there doesn't seem to be a way to look up users like you can with the portal. Its not possible for me to get the ID for Alice so I can send her ID in the payload. I can grab IDs from the browser traffic but that's not API friendly. 

2 solutions I have in mind are:

* expose an api endpoint to look up users by name. I can then get their id and use it to create groups.

```
/api/users/lookupuser/alice100
```

* change the group create payload to accept name instead of id . When you receive the name you could do a look up behind the scenes like the portal

```
{
  "name": "some-group",
  "email": "test@example.com",
  "description": "an example group", 
  "members": [
    {
      "id": "alice100"
    }
  ],
  "admins": [
    {
      "id": "alice100"
    }
  ]
}
```

**Comment by britneywright** [comment] 2019-06-14 15:51
I think we could change the payload to be the user names rather than ID.  One thing to keep in mind, in the portal if we don't find an existing user based on the user name, we look it up and try to create a new user in the database. This won't be possible on the API side, it will only look at the existing users in the database.

**Comment by remerle** [comment] 2020-09-04 19:01
This goes hand-in-hand with #930. I think we should provide an endpoint that simply returns the ID of a user given the username. We already support adding any user to a group by username in the portal.

Similar to #930, we should have an endpoint `GET /users/<username>` which returns `id` and `userName`.

```json
{
    "id": "<user_id>",
    "username": "<username>"
}
```

**Comment by pauljamescleary** [comment] 2020-09-08 12:29
@remerle Should this be closed as a duplicate of #930, or was there additional work here?

**Comment by remerle** [comment] 2020-09-08 12:48
@pauljamescleary this is adding the reverse lookup `username->id`. They can, and probably should, be done together with #930.

I was hesitant with this one because it allows for discovering which users exist in the system. However, since this is behind auth, that discovery is possible already through the portal. We need to be sure, though, that we only expose the `id`. I don't want to leak any info about the user other than the fact that their username has an `id` in VinylDNS.

**Comment by nspadaccino** [comment] 2022-05-25 13:00
@remerle I think we can close this issue, as the feature has been added as part of https://github.com/vinyldns/vinyldns/issues/930

**Closed** 2022-08-05 18:25 UTC
Labels: kind/enhancement, status/ready, area/api
