### ISSUE TITLE
Potentially move ldap authenticator to core, and move creds and login routes to api

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#215] opened 2018-09-18 18:26 UTC
**Motivation**
Right now the api is heavily dependent on users signing into the portal first and getting their credentials. Would like to discuss moving this code to the api, and making the portal 100% a web client that is not necessary to use vinyldns 

**Scope of change**
Would need to refactor the ldap authenticator to get rid of play framework specific code, then move it to the core module. Then add three routes to the api: login, download creds, and regenerate creds. Then the portal can hit the api login route when logging in.

**Comment by rebstar6** [comment] 2018-10-01 19:51
this has come up before, with mixed conclusions. Part of the problem is that we require the AWS signing on the api requests - if someone doesnt yet have a key, they cant do that. So, lacking that, what do they provide in the request? presumably their LDAP login info, but that means sending along the password too. Then what info are we comfortable sending back, and how should that be presented (unencrypted secrets? probably no good).

Worth thinking about, but I think last time this came up we concluded its not the worst thing to require at lease a basic portal for credential management

**Comment by nimaeskandary** [comment] 2018-10-01 20:00
@rebstar6 Understandable, in the portal at least usernames and passwords are already sent to the portal nodes over https, so presuming that is safe, then we could send the same info to the api instead of the portal, so same amount of time having their info being sent over the wire.

I guess in terms of security, it may introduce another layer in which their secrets have to travel unprotected, depending on how you implement it. Instead of the portal node -> pc, it may have to be api -> portal node -> pc, but alternatively, since we played around with single page portal apps before, the front end web code could be written to talk to the api directly, and could be api -> pc.

Benefits include other clients being able to make users for the first time. There are other cli's for example, like the docker and notary cli, which have users login with their website credentials right in their console. It also consolidates vital functionality into the api project

**Comment by pauljamescleary** [comment] 2018-10-03 19:42
I think the vision here is, rather than moving the ldap authenticator to core, to support dual authentication (JWT and SIG4) and just have the "portal" be a scalajs app hosted out of the same akka http server.

This way we can reduce our operational footprint (we are so low volume it doesn't make sense to have two separate things to operate) and simplify deployment.

**Comment by pauljamescleary** [comment] 2020-09-03 20:18
Recommend closing and revisiting with the portal / move to Scala 3

**Comment by remerle** [comment] 2020-09-04 17:15
Closing. To be revisited as part of the overhaul incoming with #967

**Closed by remerle** 2020-09-04 17:15 UTC
Labels: 🗣discussion, 🚧 maintenance, 🚫 wontfix
