### ISSUE TITLE
Allow all users to see any existing group

### ISSUE THREAD

**Issue by britneywright** [vinyldns/vinyldns#642] opened 2019-05-22 17:07 UTC
**Is your feature request related to a problem? Please describe.**
We want to open up read-only access of data in VinylDNS. This scope of this card is limited to individual groups. A separate card will be created for the list groups endpoint.

**Describe the solution you'd like**
Allow any user to see any existing group they request.

They should be able to see the specified group as well as the members and admins, but they should not be able to update or delete the group.

**Additional context**
I believe the endpoints this effects are:
- get group
- list group admins
- list group members
- list group activity

we may want to include and return an access level check that notes if the requesting user is a super user, group admin, group member, or none.

**Comment by nspadaccino** [comment] 2022-08-05 18:22
Duplicate of https://github.com/vinyldns/vinyldns/issues/1088
Resolved by https://github.com/vinyldns/vinyldns/pull/1097

**Closed by nspadaccino** 2022-08-05 18:22 UTC
Labels: area/portal, area/api
