### ISSUE TITLE
Most basic read only user

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns#368] opened 2018-11-20 17:21 UTC
- Add boolean on the user type for `supportUser` (or whatever we wanna call it). This will need to be stored in the protobuf, so note that. Default to false.
- Treat all GETs for this user as if they are super users
- Treat all PUTs for this user as if they are a normal user (no extra access)

**Comment by nimaeskandary** [comment] 2018-11-26 16:40
Note: duplicate of https://github.com/vinyldns/vinyldns/issues/74

**Comment by rebstar6** [comment] 2018-11-26 17:15
working card for #74

**Closed** 2018-12-17 14:59 UTC
